# Generated by Django 4.2.4 on 2023-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
