# Generated by Django 4.2.4 on 2023-09-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
