# Generated by Django 4.2.4 on 2023-09-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_reply_replied_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='response_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_from_repl', to='board.response'),
        ),
    ]
